name: SceneTools-CI

on:
  workflow_dispatch:

jobs:
  sync-repository:
    name: Synchronize private repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: actions-template-sync
        uses: AndreasAugustin/actions-template-sync@v1.1.1
        with:
          github_token: ${{ secrets.ST_SYNC_TOKEN }}
          source_repo_path: rlty-live/SceneTools
          upstream_branch: main
          source_repo_ssh_private_key: ${{ secrets.SCENETOOLS_REPO_SSH_PRIVATE_KEY }}
